# (C) 2026 Rodrigo Rodrigues da Silva <rodrigo@flowlexi.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

from __future__ import annotations

from typing import Any, Protocol, Sequence


IndexRecord = tuple[str, dict[str, Any], str]
SearchHit = tuple[str, float]


class VectorBackend(Protocol):
    def initialize(self) -> None: ...
    def index(self, records: list[IndexRecord]) -> None: ...
    def search(self, vector: Sequence[float], k: int) -> list[SearchHit]: ...
    def delete(self, rids: list[str] | str) -> None: ...
    def lookup(self, rids: list[str]) -> dict[str, Any]: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
